### ISSUE TITLE
Change color of the off now (red is to hard!)

### ISSUE THREAD

**Issue by mrVanDalo-springer** [mrVanDalo/stepp0r#68]

**Comment by mrVanDalo** [comment]
It's hard because the launchpad is limited on colors.

**Comment by mrVanDalo** [comment]
This might be part of an bigger issue, later, when the interface to adress more than device (akai, for example).

**Comment by mrVanDalo** [comment]
But I'm closing this because the color scheme of the pattern editor is Ok for now.
