### ISSUE TITLE
Show the velocity with a color

### ISSUE THREAD

**Issue by Tumulte** [mrVanDalo/stepp0r#72]
Since you are using paler orange for the note columns, ou might use green to show lower velocity notes...

To be fair I'd do the oposite : another color for the other column row, and paler yellow for lower velocity

**Comment by mrVanDalo** [comment]
There is only a very limited amount of color I can use. 16 of them and most of them look very similar (if it's not super dark) 

I also thought of this the other day, but showing the elements in the pattern area (the 32 button thing) is a bit over the top and will not help you while making music. Using color to see the delay have more benefit but again the launchpad does not have enough colors :(

**Comment by mrVanDalo** [comment]
Sorry to hard. :(

**Comment by mrVanDalo-springer** [comment]
10:38 <+Tumulte> palo: I suggested paler yellow for lower velocity and some other color for the other columns
10:39 <+Tumulte> probably red for the main note column with paler variations for lower velocity
10:39 <+Tumulte> and pale yellow for other note columns
